# Site settings
name: Less Or More
email: 479736308@qq.com
author: chenjinghao
url: https://github.com/flyGeneral/flyGeneral.github.io
resume_site: https://github.com/flyGeneral/flyGeneral.github.io/
github: https://github.com/flyGeneral/
baseurl: ""
description: Actually, less is more!
meta_description: 陈景灏;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: flyGeneral

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

